package step4_TestException;

public class TestException3 {

	public static void main(String[] args) {
		/*
		 * ?덉? 諛쒖깮 ?덉긽吏?먯? try濡?泥섎━?섍퀬
		 * ?대떦 ?덉쇅?????泥섎━??catch濡?泥섎━?쒕떎.
		 * ????遺紐⑦??낆씤 Exception 泥섎━?섎뒗 諛⑹븞怨?援ъ껜?곸씤 ?덉쇅??낆씤
		 * ArrayIndexOutOfBoundsException濡?泥섎━?섎뒗 諛⑹븞???? ?⑥젏? 臾댁뾿?쇨퉴?
		 * 1. 遺紐???낆쑝濡?泥섎━?섎㈃ 留롮? ?덉쇅瑜??섎굹??catch濡?泥섎━?????덈떎.
		 *    ??寃쎌슦 援ъ껜???덉쇅??????泥섎갑?덉쓣 留덈젴?섍린 ?대젮???⑥젏???덈떎.
		 * 2. 援ъ껜?곸씤 ?대떦 ?덉쇅 ?대옒?ㅻ줈 泥섎━?섎㈃ 耳?댁뒪蹂꾨줈 留롮? ?덉쇅 泥섎━媛 ?꾩슂?섏?留?
		 *    ?덉쇅?????援ъ껜?곸씤 泥섎━諛⑹븞??留덈젴?????덈떎.
		 * 3. ?꾩쓽 ?λ떒?먯씠 議댁옱?섎?濡??섎굹??try{}???щ윭媛쒖쓽 catch瑜??뺤쓽?섎뒗 寃껋쑝濡?
		 *    ?닿껐 --> TestException4
		 *    @param args
		 */
		int m[] = new int[3];
		
		try {
			System.out.println(m[3]);					
		} catch(ArrayIndexOutOfBoundsException ie){
			System.out.println("諛곗뿴 踰붿쐞瑜?珥덇낵?섏뿬 異쒕젰 遺덇?");
		}
		System.out.println("?꾨줈洹몃옩 ?뺤긽?숈옉!");
	}
}